name: freebsd

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  bsd-x86:
    if: "github.repository == 'OpenMathLib/OpenBLAS'"
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v6
     
     - name: build
       id: bsd_x86_64
       uses: vmactions/freebsd-vm@v1
       with:
        usesh: true
        prepare: |

        run: |
          freebsd-version
          sysctl hw.ncpu
          pkg install -y gmake gcc15
          gmake CC=gcc15 FC=gfortran15
          
